### ISSUE TITLE
Publish action failed for MacOS

### ISSUE THREAD

**Issue by iishiishii** [NeuroDesk/neurodesk-app#36]
Publish action failed with error:
```
Adding conda path to PATH
  undefined
  Error: The "path" argument must be of type string. Received undefined
```

https://github.com/s-weigand/setup-conda/issues/432

**Comment by stebo85** [comment]
I set macos-12 as a temporary workaround until the plugin has a proper workaround for macos-13 and 14

**Comment by iishiishii** [comment]
macos-latest works now
